/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectdb;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author ASUS
 */
public class ThemeChange extends javax.swing.JFrame {

    /**
     * Creates new form ThemeChange
     */
    
    static ImageIcon image;
    
    public ThemeChange() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        theme1 = new javax.swing.JButton();
        theme2 = new javax.swing.JButton();
        theme3 = new javax.swing.JButton();
        theme4 = new javax.swing.JButton();
        imagefield = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Theme Change");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 80, 30));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 90, 30));

        theme1.setBackground(new java.awt.Color(0, 204, 255));
        theme1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        theme1.setForeground(new java.awt.Color(255, 255, 255));
        theme1.setText("Theme1");
        theme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theme1ActionPerformed(evt);
            }
        });
        getContentPane().add(theme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 80, 30));

        theme2.setBackground(new java.awt.Color(0, 204, 255));
        theme2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        theme2.setForeground(new java.awt.Color(255, 255, 255));
        theme2.setText("Theme2");
        theme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theme2ActionPerformed(evt);
            }
        });
        getContentPane().add(theme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 80, 30));

        theme3.setBackground(new java.awt.Color(0, 204, 255));
        theme3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        theme3.setForeground(new java.awt.Color(255, 255, 255));
        theme3.setText("Theme3");
        theme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theme3ActionPerformed(evt);
            }
        });
        getContentPane().add(theme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 80, 30));

        theme4.setBackground(new java.awt.Color(0, 204, 255));
        theme4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        theme4.setForeground(new java.awt.Color(255, 255, 255));
        theme4.setText("Theme4");
        theme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theme4ActionPerformed(evt);
            }
        });
        getContentPane().add(theme4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 80, 30));
        getContentPane().add(imagefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectdb/icon/pic2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 685));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void close(){

WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);

}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(i==0){
        close();
        //JOptionPane.showMessageDialog(null, "Success !");
        Settings st=new Settings();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
        else{
        close();
        Settings st=new Settings();
        st.storeImg(image);
        st.setVisible(true);
        this.dispose();
        }
    }
       
    private void theme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theme1ActionPerformed
        // TODO add your handling code here:
        
        image=new ImageIcon(getClass().getResource("/connectdb/theme/theme1.jpg"));
        //imagefield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectdb/theme/theme1.jpg")));
        imagefield.setIcon(image);
       
    }//GEN-LAST:event_theme1ActionPerformed

    private void theme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theme2ActionPerformed
        // TODO add your handling code here:
       image=new ImageIcon(getClass().getResource("/connectdb/theme/theme2.jpg"));
       imagefield.setIcon(image);
    }//GEN-LAST:event_theme2ActionPerformed

    private void theme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theme3ActionPerformed
        // TODO add your handling code here:
       image=new ImageIcon(getClass().getResource("/connectdb/theme/theme3.jpg"));
       imagefield.setIcon(image);
    }//GEN-LAST:event_theme3ActionPerformed

    private void theme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theme4ActionPerformed
        // TODO add your handling code here:
       image=new ImageIcon(getClass().getResource("/connectdb/theme/theme4.png"));
       imagefield.setIcon(image);
    }//GEN-LAST:event_theme4ActionPerformed

    int i=0;
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        i=1;
        if (image.equals("")){}
        else{    
        WriteMessage wr=new WriteMessage();
        JOptionPane.showMessageDialog(null, "Saved!");
        //close();
        //wr.setVisible(true);
        //this.dispose();
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemeChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton theme1;
    private javax.swing.JButton theme2;
    private javax.swing.JButton theme3;
    private javax.swing.JButton theme4;
    // End of variables declaration//GEN-END:variables
}
